LogLevel: 1
# Proxy: http://127.0.0.1:8080 # Uncomment to tunnel traffic through proxy
Workers: 10
Requests:
  - Path: 'https://www.test.com/test'
    Method: 'get'
    Params:
      - Name: param1
        Type: ipv4
      - Name: param2
        Type: email
  - Path: 'https://www.test.com/test'
    Method: 'post'
    Headers:
      test: "test"
    Params:
      Name: param1
      Type: creditCard
  
