LogLevel: 2
Proxy: http://127.0.0.1:8080 # Uncomment to tunnel traffic through proxy
Workers: 1
Requests:
  - Path: 'https://www.test.com/sd/snd.php'
    Method: 'post'
    Headers:
      content-type: application/json; charset=UTF-8
    Params:
      - Name: number
        Type: phone
      - Name: number
        Type: creditCard  
